// file: src/actions/types.js
export const FETCH_COMPETITIONS = "FETCH_COMPETITIONS";
export const FETCH_CLUBS = "FETCH_CLUBS"
export const FETCH_HISTORICAL_TABLE = "FETCH_HISTORICAL_TABLE";
export const FETCH_MOCK_SUPER_LEAGUE_TABLE = "FETCH_MOCK_SUPER_LEAGUE_TABLE";
export const FETCH_POST = "FETCH_POST";
export const TABLE_SIZE_TO_FIT = "TABLE_SIZE_TO_FIT";
export const TABLE_AUTO_SIZE_ALL = "TABLE_AUTO_SIZE_ALL";
